name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/geigi/cozy-ci:main
    
    steps:
    - uses: actions/checkout@v4
      run: |
        pytest
